[workspace]
members = [
    "node/solo",
    "node/para",
    "runtime/solo", 
    "runtime/para", 
    "integration-wrapper"
]
exclude = ["contracts/genesis-dao-traits", "contracts/base-genesis-dao"]
[profile.release]
panic = "unwind"