[workspace]
members = [
	"node",
	"runtime",
	"integration-wrapper",
	]
default-members = [
	"node",
	"runtime",
	]
exclude = [
	"contracts/genesis-dao-traits",
	"contracts/base-genesis-dao",
	"pallets/hookpoints/contract",
	"pallets/hookpoints/hookpoint-cli"
	]
[profile.release]
panic = "unwind"
