[workspace]
members = [
    "node/solo",
    "runtime/solo",
    "tests/chain-extensions",
    "contracts/extensions/dao-assets-contract",
    "contracts/extensions/vote-escrow-contract",
]
resolver = "2"

[profile.release]
panic = "unwind"
