[workspace]
members = [
    "node/solo",
    "runtime/solo",
    "tests/chain-extensions",
    "pallets/dao-assets",
    "pallets/dao-core",
    "pallets/dao-votes",
]
resolver = "2"

[profile.release]
panic = "unwind"
