[workspace]
members = [
    "node/solo",
    "node/para",
    "runtime/solo", 
    "runtime/para", 
    "integration-wrapper"
]
exclude = [
    "contracts/hooks/genesis-dao-contract-tests",
    "contracts/hooks/genesis-dao-contract-traits",
]
[profile.release]
panic = "unwind"