[workspace]
members = [
    "node/solo",
    "runtime/solo",
    "integration-wrapper",
]
default-members = [
    "node/solo",
    "runtime/solo",
]
exclude = [
    "contracts/**",
]

[profile.release]
panic = "unwind"
