services:
  chain:
    build: .
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/genesis-dao/.cargo

  app:
    build: https://github.com/deep-ink-ventures/genesis-dao-service.git#main
    command: [ "web" ]
    ports:
      - "8000:8000"
    depends_on: &deps
      - chain
      - db
      - cache
    environment:
      - APPLICATION_STAGE=development
      - DATABASE_HOST=db
      - REDIS_HOST=cache
      - BLOCKCHAIN_URL=ws://chain:9944/

  listener:
    build: https://github.com/deep-ink-ventures/genesis-dao-service.git#main
    command: [ "listener" ]
    depends_on: *deps
    environment:
      - APPLICATION_STAGE=development]
      - DATABASE_HOST=db
      - REDIS_HOST=cache
      - BLOCKCHAIN_URL=ws://chain:9944/

  worker:
    build: https://github.com/deep-ink-ventures/genesis-dao-service.git#main
    command: [ "worker" ]
    depends_on: *deps
    environment:
      - APPLICATION_STAGE=development
      - DATABASE_HOST=db
      - REDIS_HOST=cache
      - BLOCKCHAIN_URL=ws://chain:9944/

  db:
    image: postgres:14.1-alpine
    command: -p 5432
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=core
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis:5-alpine
    command: --port 6379
    ports:
      - 6379:6379

  web:
    build:
      context: https://github.com/deep-ink-ventures/genesis-dao-frontend.git#main
      args:
        ENVIRONMENT: dockerized
    ports:
      - 3000:3000
    depends_on:
      - chain
      - app

volumes:
  db:
