[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
blake2 = "0.10.6"
proc-macro2 = "1.0.66"
quote = "1.0.31"
syn = { version = "2.0.26", features = ["full", "parsing", "extra-traits"] }

#[[test]]
#name = "tests"
#path = "tests